"""H5545 — XSS-hardening regression gate for the generated colocation page.

The page `colocation/index.html` is GENERATED by scripts/build_colocation_page.py
(INDEX_HTML template). This test pins the hardening contract on the committed
artifact AND proves esc()/safeUrl() behavior by evaluating them in node:

  1. static sink coverage — every data-bearing innerHTML interpolation in the
     leafEl/box render paths must pass through esc(); data-bearing hrefs must
     pass through esc(safeUrl(...)).
  2. JS syntax gate — the embedded <script> must parse (node --check).
  3. behavioral eval — esc() neutralizes markup/attr breakouts, safeUrl()
     drops non-http(s) schemes (javascript:/data:/...).

Local-only (matches this suite's convention); node part skips if node absent.
"""
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
PAGE = REPO / "colocation" / "index.html"
GENERATOR = REPO / "scripts" / "build_colocation_page.py"

HAS_NODE = shutil.which("node") is not None


def _page_src() -> str:
    assert PAGE.exists(), f"generated page missing: {PAGE}"
    return PAGE.read_text(encoding="utf-8")


# ---------------------------------------------------------------- 1. static


def test_generator_template_in_sync_with_artifact():
    """The committed artifact must carry the hardened template markers —
    if someone regenerates from an unhardened template these vanish."""
    src = _page_src()
    gen = GENERATOR.read_text(encoding="utf-8")
    for marker in (
        "function safeUrl(u)",
        "esc(safeUrl(c.scan))",
        "esc(lemmaHref(cur,w.slp1,c.c))",
        "esc(LABELS[cur])",
        "Failed to load '+esc(cur)",
        "esc(hits.length)",
    ):
        assert marker in src, f"artifact missing hardening marker: {marker}"
        assert marker in gen, f"generator template missing hardening marker: {marker}"


def test_esc_covers_single_quote():
    src = _page_src()
    m = re.search(r"function esc\(x\)\{.*?\}", src)
    assert m, "esc() not found"
    body = m.group(0)
    assert "/[&<>\"']/" in body, "esc() must escape single quotes"
    assert "&#39;" in body, "esc() must map ' to &#39;"


def test_no_unescaped_data_href_interpolation():
    """Data-bearing hrefs must never be interpolated without esc(safeUrl(...))."""
    src = _page_src()
    assert re.search(r'href="\'\+c\.scan', src) is None, \
        "raw c.scan in href without esc(safeUrl())"
    assert re.search(r'href="\'\+lemmaHref\(', src) is None, \
        "raw lemmaHref in href without esc()"


# ------------------------------------------------------- 2. JS syntax gate


def _embedded_script(src: str) -> str:
    m = re.search(r"<script>(.*)</script>", src, re.S)
    assert m, "embedded <script> block not found"
    return m.group(1)


@pytest.mark.skipif(not HAS_NODE, reason="node not available")
def test_embedded_script_parses():
    script = _embedded_script(_page_src())
    with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False,
                                     encoding="utf-8") as f:
        f.write(script)
        path = f.name
    r = subprocess.run(["node", "--check", path], capture_output=True, text=True)
    assert r.returncode == 0, f"generated page script has a JS syntax error:\n{r.stderr}"


# --------------------------------------------------------- 3. behavior eval


def _extract_fn(src: str, name: str) -> str:
    # both helpers are single-line definitions in the generated page
    m = re.search(rf"^function {name}\(.*$", src, re.M)
    assert m, f"{name}() not found in generated page"
    return m.group(0)


@pytest.mark.skipif(not HAS_NODE, reason="node not available")
def test_esc_and_safeurl_behavior():
    src = _page_src()
    harness = (
        _extract_fn(src, "esc")
        + "\n"
        + _extract_fn(src, "safeUrl")
        + "\nconst cases=" + json.dumps({
            "esc_script": ["esc", "<script>alert(1)</script>"],
            "esc_attr_breakout": ["esc", '" onmouseover="alert(1)'],
            "esc_single_quote": ["esc", "it's"],
            "esc_amp": ["esc", "a&b"],
            "safe_js": ["safeUrl", "javascript:alert(1)"],
            "safe_data": ["safeUrl", "data:text/html,<script>alert(1)</script>"],
            "safe_vbs": ["safeUrl", "vbscript:msgbox(1)"],
            "safe_relative": ["safeUrl", "/etc/passwd"],
            "safe_https": ["safeUrl", "https://sanskrit-lexicon.uni-koeln.de/scans/PWGScan/2020/web/webtc/servepdf.php?page=1"],
            "safe_https_upper": ["safeUrl", "HTTPS://example.com/x"],
            "combo_attr": ["esc(safeUrl(x))", 'https://a/"onmouseover=alert(1)'],
        }) + """
const out={};
for (const [k,[fn,arg]] of Object.entries(cases)) {
  out[k] = fn==="esc" ? esc(arg) : fn==="safeUrl" ? safeUrl(arg) : esc(safeUrl(arg));
}
process.stdout.write(JSON.stringify(out));
""")
    with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False,
                                     encoding="utf-8") as f:
        f.write(harness)
        path = f.name
    r = subprocess.run(["node", path], capture_output=True, text=True, timeout=30)
    assert r.returncode == 0, f"node harness failed:\n{r.stderr}"
    out = json.loads(r.stdout)

    # esc(): no raw markup / attr quotes survive
    assert "<script>" not in out["esc_script"]
    assert "&lt;script&gt;" in out["esc_script"]
    assert '"' not in out["esc_attr_breakout"]
    assert "&quot;" in out["esc_attr_breakout"]
    assert out["esc_single_quote"] == "it&#39;s"
    assert out["esc_amp"] == "a&amp;b"

    # safeUrl(): only http(s) survives
    assert out["safe_js"] == ""
    assert out["safe_data"] == ""
    assert out["safe_vbs"] == ""
    assert out["safe_relative"] == ""
    assert out["safe_https"].startswith("https://")
    assert out["safe_https_upper"].startswith("HTTPS://")  # case-insensitive allow

    # combo: scheme-passing URL can still not break the double-quoted attribute
    assert '"' not in out["combo_attr"]
    assert "&quot;" in out["combo_attr"]


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v"]))
