#!/usr/bin/env python
"""Narrow A¬G to the defensible csl-inflect give-back set (A3 / H3782).

`build_morphology_attestation_audit_inflections.py` produces the expensive join once
(~27 min over 6.9M generated rows x 5.7M tokens). This is the cheap analysis over its
output: it reads `morph_attest_infl_AnG.tsv` and answers the only question a give-back
consumer actually has — **which attested forms are worth handing to csl-inflect as engine
gaps?**

`paradigm_gap` (94,018 rows) is not that set. It overstates the engine's failures three
times over, and each subtraction is measured here rather than asserted:

  1. **Verbs.** `inflections` carries 222,736 nominal lemmas against 680 verbal, so finite
     verbs are territory the Cologne nominal tables never claimed. A verb-shaped miss is
     out-of-scope, not a defect.
  2. **Sandhied-surface-only forms.** A paradigm generator emits *unsandhied* forms. A key
     attested only as a sandhied surface is an artefact of the attested side.
  3. **Bare stems and citation forms.** Where the attested token's key equals its own
     lemma's key, DCS is tagging a bound stem or compound member (`rājñ-` for `rājan`,
     `ātma-` for `ātman`, `vāc`, `manas`), not an inflected word. A generator that emits
     inflected cells legitimately never emits these, so they are not missing cells either.

What survives all three is the candidate set. Everything subtracted is reported with its
count, so the narrowing can be audited and reversed, and nothing is silently dropped.

Deterministic, no network, read-only on the TSV.
"""
import argparse
import collections
import csv
import os
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _github_root(root):
    """Locate the org checkout root (see the sibling audit script for why this probes)."""
    env = os.environ.get("GITHUB_ROOT")
    if env:
        return Path(env)
    for cand in (root.parent, root.parent / "GitHub", root.parent.parent,
                 root.parent.parent / "GitHub"):
        if (cand / "sanskrit-util").is_dir():
            return cand
    sys.exit("cannot locate the GitHub org root; set GITHUB_ROOT")


sys.path.insert(0, str(_github_root(ROOT) / "sanskrit-util" / "py"))
from sanskrit_util import form_key  # noqa: E402

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

OUT = ROOT / "data" / "concordance"
ANG_TSV = OUT / "morph_attest_infl_AnG.tsv"
CAND_TSV = OUT / "morph_giveback_candidates.tsv"
REPORT = OUT / "MORPHOLOGY_GIVEBACK_CANDIDATES_REPORT.md"

SAMPLE_N = 20


def human(n):
    return "{:,}".format(n)


def pct(a, b):
    return "0.00%" if not b else "%.2f%%" % (100.0 * a / b)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sample", type=int, default=SAMPLE_N)
    args = ap.parse_args()

    if not ANG_TSV.exists():
        sys.exit("missing %s — run build_morphology_attestation_audit_inflections.py first"
                 % ANG_TSV)

    t0 = time.time()
    n = collections.Counter()
    dropped_upos = collections.Counter()
    candidates = []

    with ANG_TSV.open(encoding="utf-8", newline="") as f:
        for r in csv.DictReader(f, delimiter="\t"):
            n["ang"] += 1
            if r["triage_class"] != "paradigm_gap":
                continue
            n["paradigm_gap"] += 1

            if r["dcs_upos"] == "VERB":
                n["drop_verb"] += 1
                continue
            if "unsandhied" not in r["attested_via"]:
                n["drop_sandhi_only"] += 1
                continue
            lemma = r["dcs_lemma"]
            if lemma and form_key(lemma) == r["form_key"]:
                n["drop_stem_or_citation"] += 1
                dropped_upos[r["dcs_upos"] or "(none)"] += 1
                continue

            n["candidate"] += 1
            candidates.append(r)

    candidates.sort(key=lambda r: (-int(r["evidence_count"]), r["attested_form"]))

    header = ["attested_form", "form_key", "dcs_lemma", "dcs_upos", "target_locus",
              "evidence_count", "tense_caveat"]
    with CAND_TSV.open("w", encoding="utf-8", newline="") as f:
        f.write("\t".join(header) + "\n")
        for r in candidates:
            f.write("\t".join(r[k] for k in header) + "\n")

    by_pos = collections.Counter(r["dcs_upos"] or "(none)" for r in candidates)
    caveat = sum(1 for r in candidates if r["tense_caveat"] == "1")
    today = time.strftime("%d-%m-%Y")

    L = []
    w = L.append
    w("# csl-inflect give-back candidates — the defensible subset of A¬G (H3782)")
    w("")
    w("_Auto-generated by [`scripts/analyze_morph_giveback_set.py`](https://github.com/"
      "gasyoun/kosha/blob/main/scripts/analyze_morph_giveback_set.py) (H3782, Opus 5 "
      "`claude-opus-5`) over [`morph_attest_infl_AnG.tsv`](https://github.com/gasyoun/kosha/"
      "blob/main/data/concordance/morph_attest_infl_AnG.tsv). Re-derivable in seconds; the "
      "expensive join it consumes is a separate script._")
    w("")
    w("_Created: %s · Last updated: %s_" % (today, today))
    w("")
    w("## The narrowing, measured")
    w("")
    w("A¬G is **%s** keys and `paradigm_gap` is **%s** of them. Neither is the number to "
      "hand csl-inflect. Three subtractions, each one a scope fact about the generator or "
      "an artefact of the attested side rather than an engine defect:"
      % (human(n["ang"]), human(n["paradigm_gap"])))
    w("")
    w("| Step | Rows | Why it is not an engine gap |")
    w("|---|---:|---|")
    w("| `paradigm_gap` | %s | lemma known to the generator, this form never generated |"
      % human(n["paradigm_gap"]))
    w("| − DCS `upos=VERB` | −%s | `inflections` holds 680 verbal lemmas against 222,736 "
      "nominal; finite verbs are scope it never claimed |" % human(n["drop_verb"]))
    w("| − attested only as a sandhied surface | −%s | a generator emits unsandhied forms; "
      "this is an artefact of the attested key |" % human(n["drop_sandhi_only"]))
    w("| − bare stem / citation form (`form_key` == lemma's `form_key`) | −%s | DCS tags "
      "bound stems and compound members as tokens (`rājñ-`, `ātma-`, `vāc`, `manas`); a "
      "generator emitting inflected cells never emits these |"
      % human(n["drop_stem_or_citation"]))
    w("| **= give-back candidates** | **%s** | **%s of `paradigm_gap`, %s of A¬G** |"
      % (human(n["candidate"]), pct(n["candidate"], n["paradigm_gap"]),
         pct(n["candidate"], n["ang"])))
    w("")
    w("**The headline number is the last row, not the first.** Quoting A¬G = %s as "
      "\"forms the engine misses\" overstates the actionable set by **%.0fx**."
      % (human(n["ang"]), n["ang"] / max(1, n["candidate"])))
    w("")
    w("R-C4: **%s** of the %s candidates (%s) carry `tense_caveat=1` (DCS `Tense=Past` "
      "conflates aorist and perfect) — flagged, not excluded."
      % (human(caveat), human(n["candidate"]), pct(caveat, n["candidate"])))
    w("")
    w("## Candidates by DCS part of speech")
    w("")
    w("| upos | rows | share |")
    w("|---|---:|---:|")
    for k, v in by_pos.most_common():
        w("| %s | %s | %s |" % (k, human(v), pct(v, n["candidate"])))
    w("")
    w("## Top %d candidates by corpus attestation" % args.sample)
    w("")
    w("Highest-frequency first, so the give-back can be triaged by how much corpus text each "
      "missing form would explain. Each row is a real gap iff the form occurs in DCS at the "
      "cited locus **and** `inflections` really lacks it for that lemma — both checkable.")
    w("")
    w("| # | attested form | form_key | DCS lemma | upos | locus | occ |")
    w("|---:|---|---|---|---|---|---:|")
    for i, r in enumerate(candidates[:args.sample], 1):
        w("| %d | `%s` | `%s` | `%s` | %s | `%s` | %s |"
          % (i, r["attested_form"], r["form_key"], r["dcs_lemma"], r["dcs_upos"],
             r["target_locus"], human(int(r["evidence_count"]))))
    w("")
    w("**Two cross-checks on this list, one reassuring and one not.** Reassuring: the head is "
      "dominated by pronoun dative/locative cells (`asmai` < `idam`, `tasmai`/`tasyai` < "
      "`tad`, `etasmin` < `etad`, `amum` < `adas`) and irregular feminine/consonant stems "
      "(`striyaḥ` < `strī`, `śriyam` < `śrī`, `āpo` < `ap`) — exactly where MW-inflect is "
      "known to be weak, and `inflections` already carries a hand-made "
      "`source='curated-gita-pronoun'` patch of 153 rows, which is independent evidence that "
      "pronouns are a real gap rather than an artefact of this method. Not reassuring: the "
      "bare-stem filter above matches only where the token's key equals its lemma's key "
      "exactly, so **allomorphic** bound stems still pass it — `rājñ` (< `rājan`) and `ātma` "
      "(< `ātman`) sit at ranks 2 and 3. The head of this list needs human triage before "
      "hand-off; it is a candidate set, not a defect list.")
    w("")
    w("## What was dropped as a bare stem — the class worth a second look")
    w("")
    w("The stem/citation subtraction is the largest of the three and the least obvious, so "
      "its composition is published too. If DCS's tokenisation of compound members is later "
      "judged to be in scope for the generator, these **%s** rows come back."
      % human(n["drop_stem_or_citation"]))
    w("")
    w("| upos | rows |")
    w("|---|---:|")
    for k, v in dropped_upos.most_common(10):
        w("| %s | %s |" % (k, human(v)))
    w("")
    w("## Output")
    w("")
    w("[`data/concordance/morph_giveback_candidates.tsv`](https://github.com/gasyoun/kosha/"
      "blob/main/data/concordance/morph_giveback_candidates.tsv) — %s rows, %s bytes, sorted "
      "by descending corpus attestation. Runtime %.1f s."
      % (human(n["candidate"]), human(os.path.getsize(CAND_TSV)), time.time() - t0))
    w("")
    w("**Routing (hard stop).** These are handed to the csl-inflect dual-engine give-back "
      "(H185) as a **queued port** — a GTD row and a pointer, never an in-pass edit to "
      "csl-inflect.")
    w("")
    w("_Dr. Mārcis Gasūns_")

    REPORT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("A¬G %s -> paradigm_gap %s -> candidates %s (verb -%s, sandhi-only -%s, stem -%s)"
          % (human(n["ang"]), human(n["paradigm_gap"]), human(n["candidate"]),
             human(n["drop_verb"]), human(n["drop_sandhi_only"]),
             human(n["drop_stem_or_citation"])))
    print("wrote %s" % REPORT)


if __name__ == "__main__":
    main()
