#!/usr/bin/env python3
"""Emit a slim JS coverage shard for concordance/panini/ from sutra_coverage_map.tsv.

W4a (H1585 / next-programme W1c): the panini page must surface all four coverage
statuses (lit · dark-unattested · dark-out-of-scope · dark-engine-gap) distinctly —
never collapsed into one "dark" bucket.

Output:
  concordance/panini/data/coverage.js  → window.COVERAGE_MAP + window.COVERAGE_STATS

Usage:
  python scripts/build_panini_coverage_shards.py
"""
from __future__ import annotations

import csv
import json
import sys
from collections import Counter
from datetime import date
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parents[1]
TSV = ROOT / "data" / "concordance" / "sutra_coverage_map.tsv"
OUT = ROOT / "concordance" / "panini" / "data" / "coverage.js"

# Four named statuses — order is load-bearing for the UI legend.
STATUSES = (
    "lit",
    "dark-unattested",
    "dark-out-of-scope",
    "dark-engine-gap",
)


def load_rows() -> list[dict]:
    if not TSV.is_file():
        raise SystemExit(f"missing coverage map: {TSV}")
    with TSV.open(encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        rows = list(reader)
    if not rows:
        raise SystemExit(f"empty coverage map: {TSV}")
    return rows


def slim(row: dict) -> dict:
    """Minimal payload for the browser — no multi-sentence scope dumps."""
    status = (row.get("status") or "").strip()
    if status not in STATUSES:
        raise SystemExit(f"unknown status {status!r} on {row.get('sutra_id')}")
    forms = int(row.get("exemplar_forms") or 0)
    loci = int(row.get("exemplar_loci") or 0)
    texts = int(row.get("texts") or 0)
    mean = row.get("mean_chain_position") or ""
    mean_f = float(mean) if mean not in ("", None) else None
    # Keep a short justification token only (first clause / first 80 chars).
    just = (row.get("scope_justification") or "").strip()
    just_short = just.split(":")[0][:80] if just else ""
    return {
        "id": row["sutra_id"].strip(),
        "text": (row.get("sutra_text_slp1") or "")[:80],
        "status": status,
        "forms": forms,
        "loci": loci,
        "texts": texts,
        "mean_pos": mean_f,
        "why": just_short,
    }


def main() -> None:
    rows = [slim(r) for r in load_rows()]
    counts = Counter(r["status"] for r in rows)
    for s in STATUSES:
        counts.setdefault(s, 0)
    # Integrity: every status string present in the emitted payload at least once
    # OR explicitly zero-counted (dark-engine-gap may be 0 — still named).
    stats = {
        "n": len(rows),
        "enumeration": "vidyut-0.4.0 Data.load_sutras() Source.Ashtadhyayi (n=3983)",
        "build_date": date.today().isoformat(),
        "source": "data/concordance/sutra_coverage_map.tsv",
        "report": "data/concordance/SUTRA_COVERAGE_BUILD_REPORT.md",
        "counts": {s: counts[s] for s in STATUSES},
        "statuses": list(STATUSES),
    }
    if stats["n"] != 3983:
        # LOG: standing enumeration is 3983; surface a warning but still emit
        # (a future recension may move the count).
        print(
            f"LOG: coverage row count {stats['n']} != standing enumeration 3983",
            file=sys.stderr,
        )

    by_adhy: dict[str, list[dict]] = {str(i): [] for i in range(1, 9)}
    for r in rows:
        adhy = r["id"].split(".", 1)[0]
        by_adhy.setdefault(adhy, []).append(r)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload_map = json.dumps(by_adhy, ensure_ascii=False, separators=(",", ":"))
    payload_stats = json.dumps(stats, ensure_ascii=False, separators=(",", ":"))
    body = (
        "/* Auto-generated by scripts/build_panini_coverage_shards.py — do not edit. */\n"
        "window.COVERAGE_STATS = " + payload_stats + ";\n"
        "window.COVERAGE_MAP = " + payload_map + ";\n"
    )
    OUT.write_text(body, encoding="utf-8")
    print(
        f"wrote {OUT.relative_to(ROOT)}  rows={stats['n']}  "
        + "  ".join(f"{s}={counts[s]}" for s in STATUSES)
        + f"  bytes={OUT.stat().st_size}"
    )


if __name__ == "__main__":
    main()
