"""build_paradigms.py — P4 Wave K2b (H183) static-tier generator for the
inflection UI (ui/ -> docs/inflect/).

Emits, from the local kosha.db (never calls a live service — RISKS.md R12):

  1. Per-stem paradigm shards — one JSON per lemma, byte-identical to what
     GET /api/v1/paradigm/<slp1>?in=slp1 returns (both call app/paradigm.py's
     build_paradigm; parity locked by tests/test_paradigms.py).
       -> docs/inflect/data/paradigms/<token>.json

  2. Reverse index buckets — the static fallback for the paste-anything box.
     Keyed by a 2-char SLP1 prefix bucket (cardToken of form_slp1[:2]); each
     bucket maps form_slp1 -> {resolved_by, analyses, forms_witnesses, lemmas}
     computed from stages 1-2 ONLY (exact `inflections` / `forms` hits). Stage-3
     vidyut segmentation is deliberately NOT baked in: it cannot run in a static
     browser, so a sandhied/compound miss honestly reports
     segmentation_available:false — the same graceful-degradation contract the
     live API exposes (and the browser falls back to the API when window.KOSHA_API
     is set). Reuses app/reverse_lookup.py's stage helpers so a static parse
     matches the API's stage-1/2 output exactly.
       -> docs/inflect/data/reverse/<bucket>.json

Scope
-----
The full attested-with-entry set is 176,099 lemmas / 242,846 paradigms (~250 MB)
— generated by --all and DEPLOYED by MG out-of-band exactly like the P2 cards
tier (A3). The committed repo ships only the --demo curated set (the H183
exit-check forms + a few common stems) so the static site at
gasyoun.github.io/kosha/inflect/ works out of the box without the full deploy.

Usage:
    python scripts/build_paradigms.py                 # --demo (default; committed)
    python scripts/build_paradigms.py --all           # full attested-with-entry set (MG deploys)
    python scripts/build_paradigms.py --limit 5000     # top-N attested-with-entry, rank order
    python scripts/build_paradigms.py --lemmas rAma,BU # explicit lemma list
    python scripts/build_paradigms.py --force          # re-emit existing shards

Idempotent: an existing paradigm shard is skipped unless --force.
"""
import argparse
import json
import sqlite3
import sys
import time
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "app"))

from paradigm import build_paradigm  # noqa: E402
from reverse_lookup import (  # noqa: E402
    _inflection_analyses, _forms_witnesses, _unified_lemmas,
)

DEFAULT_DB = ROOT / "data" / "db" / "kosha.db"
OUT_DIR = ROOT / "docs" / "inflect" / "data"

# Curated demo set: the H183 exit-check stems plus a handful of common stems so
# the committed static tier is genuinely usable, not just a single word.
#   rAma       — m_a nominal, the forward exit form
#   Bagavat    — bhagavat (m_vat), canonical stem of the reverse form bhagavān
#   Darmakzetra— dharmakṣetra, the ambiguous sandhied reverse form's stem
#   BU         — bhū, a verb paradigm showcase
#   deva, agni, guru, nadI, Atman, gaja — common teaching stems
DEMO_LEMMAS = [
    "rAma", "Bagavat", "Darmakzetra", "BU",
    "deva", "agni", "guru", "nadI", "Atman", "gaja", "kavi", "vAc",
]


def card_token(slp1: str) -> str:
    out = []
    for b in slp1.encode("utf-8"):
        out.append(chr(b) if (97 <= b <= 122) or (48 <= b <= 57) else "_%02x" % b)
    return "".join(out)


def reverse_bucket(form_slp1: str) -> str:
    """2-char SLP1 prefix bucket. Kept in sync with reverseBucket() in
    ui/src/lib/cardToken.js."""
    return card_token((form_slp1 or "")[:2])


def open_db(db_path: Path) -> sqlite3.Connection:
    con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    con.row_factory = sqlite3.Row
    return con


def select_lemmas(con, args) -> list[str]:
    if args.lemmas:
        return [x.strip() for x in args.lemmas.split(",") if x.strip()]
    if args.demo:
        # keep only demo stems that actually have inflection rows
        present = []
        for lem in DEMO_LEMMAS:
            if con.execute("SELECT 1 FROM inflections WHERE lemma_slp1=? LIMIT 1", (lem,)).fetchone():
                present.append(lem)
        return present
    # --all / --limit: attested-with-entry lemmas, frequency-rank order so a
    # partial run front-loads value (same discipline as build_static_cache).
    sql = (
        "SELECT DISTINCT i.lemma_slp1 AS lem, l.rank_all AS rank "
        "FROM inflections i "
        "JOIN entries e ON e.slp1_key = i.lemma_slp1 "
        "LEFT JOIN lemmas l ON l.slp1 = i.lemma_slp1 "
        "ORDER BY (l.rank_all IS NULL), l.rank_all ASC, i.lemma_slp1 ASC"
    )
    rows = con.execute(sql).fetchall()
    lemmas = [r["lem"] for r in rows]
    if args.limit:
        lemmas = lemmas[: args.limit]
    return lemmas


def emit_paradigms(con, lemmas, out_dir: Path, force: bool) -> int:
    pdir = out_dir / "paradigms"
    pdir.mkdir(parents=True, exist_ok=True)
    n = 0
    for lem in lemmas:
        path = pdir / f"{card_token(lem)}.json"
        if path.exists() and not force:
            continue
        para = build_paradigm(con, lem)
        if para is None:
            continue
        path.write_text(json.dumps(para, ensure_ascii=False), encoding="utf-8")
        n += 1
    return n


def _reverse_entry(con, form_slp1: str) -> dict:
    """Stage-1 (+2 fallback) reverse record for one form, matching the API's
    resolved_by contract but WITHOUT stage-3 segmentation."""
    analyses = _inflection_analyses(con, form_slp1)
    if analyses:
        return {"resolved_by": "inflections", "analyses": analyses,
                "lemmas": _unified_lemmas(con, analyses)}
    witnesses = _forms_witnesses(con, form_slp1)
    if witnesses:
        return {"resolved_by": "forms", "forms_witnesses": witnesses,
                "lemmas": _unified_lemmas(con, witnesses)}
    return {"resolved_by": None, "analyses": [], "lemmas": []}


def emit_reverse(con, lemmas, out_dir: Path, full_buckets: bool) -> int:
    """Build reverse index buckets. For the demo/limited set, index only the
    forms of the selected lemmas (a coherent, fully-working subset). With
    --all + --full-reverse, index every distinct form in the DB."""
    rdir = out_dir / "reverse"
    rdir.mkdir(parents=True, exist_ok=True)
    buckets: dict[str, dict] = {}

    if full_buckets:
        forms = [r[0] for r in con.execute("SELECT DISTINCT form_slp1 FROM inflections")]
        forms += [r[0] for r in con.execute("SELECT DISTINCT form_slp1 FROM forms")]
        form_iter = sorted(set(forms))
    else:
        seen = set()
        for lem in lemmas:
            for r in con.execute("SELECT DISTINCT form_slp1 FROM inflections WHERE lemma_slp1=?", (lem,)):
                seen.add(r[0])
            for r in con.execute("SELECT DISTINCT form_slp1 FROM forms WHERE lemma_slp1=?", (lem,)):
                seen.add(r[0])
        form_iter = sorted(seen)

    for form in form_iter:
        entry = _reverse_entry(con, form)
        if entry["resolved_by"] is None:
            continue
        buckets.setdefault(reverse_bucket(form), {})[form] = entry

    for bucket, mapping in buckets.items():
        path = rdir / f"{bucket}.json"
        if path.exists() and not full_buckets:
            # merge into an existing demo bucket rather than clobbering it
            existing = json.loads(path.read_text(encoding="utf-8"))
            existing.update(mapping)
            mapping = existing
        path.write_text(json.dumps(mapping, ensure_ascii=False), encoding="utf-8")
    return sum(len(m) for m in buckets.values())


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", type=Path, default=DEFAULT_DB)
    ap.add_argument("--out", type=Path, default=OUT_DIR)
    ap.add_argument("--all", action="store_true", help="full attested-with-entry set (MG deploys)")
    ap.add_argument("--demo", action="store_true", help="curated exit-check demo set (default)")
    ap.add_argument("--limit", type=int, default=0, help="top-N attested-with-entry, rank order")
    ap.add_argument("--lemmas", type=str, default="", help="explicit comma-separated SLP1 lemmas")
    ap.add_argument("--full-reverse", action="store_true",
                    help="with --all: index every DB form (large), not just selected lemmas")
    ap.add_argument("--force", action="store_true", help="re-emit existing shards")
    args = ap.parse_args()

    # Default to demo when no explicit scope is given.
    if not (args.all or args.limit or args.lemmas):
        args.demo = True

    con = open_db(args.db)
    t0 = time.time()
    lemmas = select_lemmas(con, args)
    print(f"[paradigms] {len(lemmas)} lemma(s) selected "
          f"({'demo' if args.demo else 'all' if args.all else 'limit/lemmas'})")

    n_para = emit_paradigms(con, lemmas, args.out, args.force)
    print(f"[paradigms] wrote {n_para} paradigm shard(s) -> {args.out / 'paradigms'}")

    full_rev = args.all and args.full_reverse
    n_rev = emit_reverse(con, lemmas, args.out, full_rev)
    print(f"[reverse] indexed {n_rev} form(s) -> {args.out / 'reverse'}"
          + (" (FULL)" if full_rev else " (selected lemmas)"))
    print(f"[done] {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
