#!/usr/bin/env python
"""H874 / roadmap W4 — Gītā inflection-engine QA against the E1 hybrid layer.

The first ATTESTED-CORPUS check of kosha's hybrid `inflections` (Cologne +
vidyut, H185/E1). For every nominal word of the Bhagavadgītā we take the GOLD
case·number·gender (from data/gita/gita_morphology_gold.tsv, H873) and ask
whether kosha's inflection paradigm for that surface form CONTAINS the attested
analysis. Classifies each word AGREE / GENDER-ONLY / DIVERGE / GAP and writes a
report + a divergence ledger. Nothing is auto-applied — divergences are a
candidate feed for a human `@DO`.

Scope: nominals (the layer E1 operates on). Finite verbs (person·tense·voice)
are reported as a coverage note, not scored — kosha's inflections table is
nominal-paradigm-centric.

Usage: python scripts/gita_inflection_qa.py
"""
import csv
import sqlite3
import sys
from collections import Counter
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8")
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT.parent / "sanskrit-util" / "py"))
from sanskrit_util import to_slp1  # noqa: E402

GOLD = ROOT / "data" / "gita" / "gita_morphology_gold.tsv"
KOSHA_DB = ROOT / "data" / "db" / "kosha.db"
if not KOSHA_DB.exists():
    GH = ROOT.parent if (ROOT.parent / "SanskritGrammar").exists() else ROOT.parent.parent
    KOSHA_DB = GH / "kosha" / "data" / "db" / "kosha.db"
REPORT = ROOT / "GITA_MORPHOLOGY_QA_REPORT.md"
LEDGER = ROOT / "data" / "gita" / "gita_inflection_divergences.tsv"

CASE = {"nom": "nom", "acc": "acc", "ins": "instr", "dat": "dat", "abl": "abl",
        "gen": "gen", "loc": "loc", "voc": "voc"}  # gold -> kosha gcase


def clean(form):
    return to_slp1(form.replace("-", "").strip().strip("'’"))


def main():
    con = sqlite3.connect(str(KOSHA_DB)); c = con.cursor()

    def analyses(form_slp1):
        return set((g, n, ge) for g, n, ge in c.execute(
            "SELECT gcase, number, gender FROM inflections WHERE form_slp1=?", (form_slp1,)))

    rows = list(csv.DictReader(open(GOLD, encoding="utf-8"), delimiter="\t"))
    NOMINAL = {"nominal", "participle", "pronoun"}
    tally = Counter()
    verbs = 0
    divergences = []
    pat = {"DIVERGE": Counter(), "GAP": Counter()}  # pattern: pronoun / compound / other

    def bucket(r):
        if r["pos"] == "pronoun":
            return "pronoun"
        return "compound" if "-" in r["lemma"] else "other"

    for r in rows:
        pos, case = r["pos"], r["case"]
        if pos == "verb":
            verbs += 1; continue
        if pos not in NOMINAL or not case:
            tally["not-scored (no case)"] += 1; continue
        gc = CASE.get(case)
        gold = (gc, r["number"], r["gender"])
        an = analyses(clean(r["form"]))
        if not an:
            tally["GAP (form absent from kosha)"] += 1
            pat["GAP"][bucket(r)] += 1
            divergences.append((r["verse"], r["form"], r["lemma"], "/".join(gold), "GAP", ""))
        elif gold in an:
            tally["AGREE"] += 1
        elif any(a[0] == gold[0] and a[1] == gold[1] for a in an):
            tally["AGREE case+number (gender differs)"] += 1
        else:
            tally["DIVERGE (case/number not in paradigm)"] += 1
            pat["DIVERGE"][bucket(r)] += 1
            koshaset = ";".join(sorted("%s.%s.%s" % a for a in an)[:6])
            divergences.append((r["verse"], r["form"], r["lemma"], "/".join(gold), "DIVERGE", koshaset))

    scored = tally["AGREE"] + tally["AGREE case+number (gender differs)"] + \
        tally["DIVERGE (case/number not in paradigm)"] + tally["GAP (form absent from kosha)"]
    present = scored - tally["GAP (form absent from kosha)"]
    agree = tally["AGREE"] + tally["AGREE case+number (gender differs)"]
    pct = lambda a, b: round(100.0 * a / b, 1) if b else 0.0

    LEDGER.parent.mkdir(parents=True, exist_ok=True)
    with open(LEDGER, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f, delimiter="\t", lineterminator="\n")
        w.writerow(["verse", "form", "lemma", "gold_case_num_gender", "class", "kosha_analyses"])
        for d in divergences:
            w.writerow(d)

    L = []
    L.append("# Gītā inflection-engine QA — gold morphology vs kosha's hybrid paradigms\n")
    L.append("_Auto-generated by scripts/gita_inflection_qa.py (H848 W4 / H874)._\n")
    L.append("The first **attested-corpus** check of kosha's Cologne+vidyut hybrid "
             "`inflections` layer (H185/E1): does the paradigm for each Bhagavadgītā "
             "nominal's surface form contain its **attested** case·number·gender?\n")
    L.append("## Headline\n")
    L.append(f"- Nominal words scored: **{scored}** (of {len(rows)} total; {verbs} finite verbs "
             "not scored — kosha's inflection table is nominal-centric).")
    L.append(f"- **Present in kosha** (form has a paradigm): {present} ({pct(present, scored)}% of scored).")
    L.append(f"- **AGREE** (attested analysis in the paradigm): **{agree} = {pct(agree, present)}% of present**, "
             f"{pct(agree, scored)}% of all scored.")
    L.append("")
    L.append("## Breakdown\n")
    L.append("| class | count | % of scored |")
    L.append("|---|--:|--:|")
    for k in ["AGREE", "AGREE case+number (gender differs)",
              "DIVERGE (case/number not in paradigm)", "GAP (form absent from kosha)",
              "not-scored (no case)"]:
        if tally[k]:
            L.append(f"| {k} | {tally[k]} | {pct(tally[k], scored)} |")
    L.append("")
    L.append("## Where the misses cluster (the finding)\n")
    dv, gp = pat["DIVERGE"], pat["GAP"]
    L.append(f"- **DIVERGE ({sum(dv.values())})** is dominated by **pronouns** "
             f"(sarvanāman): pronoun {dv['pronoun']} · compound {dv['compound']} · other {dv['other']}. "
             "kosha either leaves the pronoun form untagged (`None.None.None`) or emits a wrong cell — "
             "this **confirms + quantifies with attested text** the pronominal mis-modelling already flagged "
             "synthetically in [E1_DIVERGENCE_REPORT.md](https://github.com/gasyoun/kosha/blob/main/E1_DIVERGENCE_REPORT.md). "
             "These are prime `disputed=1` candidates.")
    L.append(f"- **GAP ({sum(gp.values())})** is dominated by **compounds** "
             f"(not held as whole inflected forms): compound {gp['compound']} · pronoun {gp['pronoun']} · other {gp['other']}. "
             "Expected — long samāsa aren't paradigm entries; a compound-splitter (vidyut-cheda) would resolve the members.")
    L.append("")
    L.append(f"## Divergence ledger ({len(divergences)} rows)\n")
    L.append("Full list: [`data/gita/gita_inflection_divergences.tsv`](https://github.com/gasyoun/kosha/blob/main/data/gita/gita_inflection_divergences.tsv) "
             "— DIVERGE = kosha has the form but not the attested case·number cell (a real paradigm "
             "disagreement, candidate `disputed`/gap-fill); GAP = form absent from kosha's inflections. "
             "**Not auto-applied** — a human `@DO` adjudicates.\n")
    L.append("Sample DIVERGE rows (attested gold vs kosha's set):\n")
    n = 0
    for d in divergences:
        if d[4] == "DIVERGE" and n < 15:
            L.append(f"- `{d[0]}` **{d[1]}** ({d[2]}) — gold `{d[3]}` ; kosha: `{d[5]}`")
            n += 1
    L.append("")
    REPORT.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print(f"scored {scored} nominals: AGREE {agree} ({pct(agree, present)}% of present), "
          f"DIVERGE {tally['DIVERGE (case/number not in paradigm)']}, GAP {tally['GAP (form absent from kosha)']}")
    print("wrote", REPORT, "and", LEDGER)


if __name__ == "__main__":
    main()
